### ISSUE TITLE
Fix NEB deposits

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#40]
## The Chore

Squid powered deposit doesnt work for NEB deposits, and the order still doesnt feel right in terms of UX.

## Tasks

- [x] Swap the order so that it reads:
  - [x] To Nebula key
  - [x] To asset 
  - [x] From address
  - [x] From chain
  - [x] From asset 
  - [x] Amount
- [x] If the user selects NEB as the To Asset then default from chain to ethereum and from asset to NEB and use normal deposit flow without Squid

**Comment by descartes1596** [comment]
These are broken .... very broken .... funds are being sent to Vega.
