### ISSUE TITLE
Build dedicated flow to buy NEB

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#42]
## The Chore

Need easy deposit from website.

## Tasks

- [ ] Build a page in the website that allow:
  - [ ] Deposit any asset from any squid chain and asset
  - [ ] Use squid to swap asset for Arbitrum USDT and deposit
  - [ ] Send IOC limit order with price determined by the slippage tolerance to convert USDT for NEB

## Additional details / background info

Console function can be use:

- Deposit flow (including fixes in #40) covers the deposit with Squid if default To Asset to NEB (Eth)
- Swap function covers submitting an IOC order at a price level determined by a user defined slippage tolerance

So maybe hide behind an even simpler screen that handles the routing or as a MVP we guide user through deposit and then swap, which might be needed since they will need the wallet to sign a TX for the swap.
