### ISSUE TITLE
Governance app showing wrong balances

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#44]
## The Chore

Connected govenance app with new ethereum connection and can see this 

![image](https://github.com/user-attachments/assets/7538d91a-4768-46d9-9f60-5ca9b858dc4d)

## Tasks

- [x] Ethereum key should be showing NEB in wallet not VEGA
- [x] Nebula wallet should be showing NEB associated not VEGA
- [x] It is detecting a balance of 2000 VEGA on my key which is not correct, it is empty, but maybe this issue goes away if above is fixed
