### ISSUE TITLE
Add asset class filter

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#58]
## The Chore

Add filter for asset class to market 

![image](https://github.com/user-attachments/assets/e5c9a271-82a9-4143-9f40-f0832c304000)

![image](https://github.com/user-attachments/assets/66ac6ef5-e61c-4643-b544-3d306b41e225)

![image](https://github.com/user-attachments/assets/5a1d0ca6-7ba9-48a1-b93e-cc8adccbe6aa)

## Tasks

- [ ] Add asset class filter dropdown to markets page
- [ ] Add asset class filter dropdown to market selector on trading page
- [ ] Add asset class to the market header

## Additional details / background info

Asset class is stored on the metadata under the tag "Class".  

Should add a capital letter to the lower case tag when displaying it.
