### ISSUE TITLE
Create a page to claim NEB airdrop

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#62]
## The Chore

There will be a NEB airdrop for anyone that had VEGA at the time of the swap.

To claim it users will need to register their ethereum and Nebula addresses so the NEB can be airdropped on Nebula.

## Tasks

- [ ] Create a simple "Claim NEB flow" on its own URL which should simply take user through
  - [ ] The normal onboarding connect page at https://trade.neb.exchange/#/invite/connect
  - [ ] A "Claim NEB" page with a big "Claim" button and some text indicating you are signing a message with your ethereum wallet to associate your NEB address for an airdrop
  - [ ] This message will be sent to some service that will be created
  - [ ] Once claimed, provide a CTAs to
    - [ ] Buy more NEB from the new "buy NEB" page
    - [ ] Go to markets

## Additional details / background info

Onboarding page example

![image](https://github.com/user-attachments/assets/fb465578-dd42-4fa8-ac87-cdd25c864c13)
