### ISSUE TITLE
Further squid deposit UX improvements

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#70]
## The Chore

Can we do more to simplify all the TOs and FROMs?

## Tasks

- [ ] Do we need the TO Key?  Just deposit to the current key ... dont know if we even need to SHOW it (you can see it right there in the top right already) and we **certainly** dont need to allow you to change it... thats just confusing ... why would I be connected as Key 1 but want to deposit to Key 2?  Makes no sense.
- [ ] If we did that then "TO asset" could just be "Asset" which would simplify that part
- [ ] What can we do about from address / chain / asset? Some ideas below

## Additional details / background info

Could we lean into Squid's presentation a bit more? They just have this "Pay" field which is easy to understand and the chain and asset are baked into the icon.

![image](https://github.com/user-attachments/assets/28c94db6-8dc2-4cf7-8a56-59f155312c89)

Then when you click it you get this two-pane UX where both the chain and the asset are selected in one step.

![image](https://github.com/user-attachments/assets/d13ea6d1-5acf-4845-8150-a9310232f65e)
