### ISSUE TITLE
Build the first proper MVP of neb.exchange

### ISSUE THREAD

**Issue by descartes1596** [Nebula-DEX/frontend-monorepo#79]
## The Chore

The page is basically just the claim which is now not even valid. 

## Tasks

- [ ] Add a trading link to nav that sends you to Nebula app
- [ ] Add a screenshot to the homepage
- [ ] Add a description of markets, mission statement, performance USPs
- [ ] Remove the claim page which is now closed
- [ ] Other?
